### PR TITLE
Add Hapijs to benchmark

### PR DESCRIPTION
**Pull request by thebergamo**

### CODE REVIEW

**Comment by thebergamo** [comment]
@nanoant  you can update the benchmark ranking?

**Comment by nanoant** [comment]
Sure, will do. Gimme couple of minutes, coz now my computer is busy doing other interesting stuff ;P

**Comment by thebergamo** [comment]
don't worries =D

**Comment by thebergamo** [comment]
@nanoant some news?

**Comment by nanoant** [comment]
@thebergamo Unfortunatelly there is some optimization problem in node js that causes very bad performance, see [results/E5-1650v2-Ubuntu-14.04LTS/hapi_01.txt](/nanoant/WebFrameworkBenchmark/blob/master/results/E5-1650v2-Ubuntu-14.04LTS/hapi_01.txt)

So I cannot really let in this into the README.md until there is some solution for that.

For more references about problem see:
- http://stackoverflow.com/questions/15422411/node-js-response-time
- http://stackoverflow.com/questions/11335510/nodejs-response-speed-and-nginx

**Comment by thebergamo** [comment]
That's very strange :(

But, I think in future, using io.js the time response improve!

thanks for reply me =D

**Pull request merged**
